
/**
 * Generates Random hands
 * e.g. "Kc Kd 3s 5s 4d"
 *
 * @author Jimmy Collins <jbc1@student.cs.ucc.ie>
 * @date Decemebr 19th 2006
 *
 * Last Update: January 2nd 2007
 */



import javax.swing.*;
import java.awt.*;
import java.awt.Dialog.*;
import java.io.*;


public class HandGenerator
{

//----------CONSTANTS----------------//

//-------CLASS VARIABLES-------------//

//------INSTANCE VARIABLES-----------//

/**
 * A random number generator
 */
private RandomNumGenerator numGen;

/**
 * A random suit generator
 */
public RandomSuitGenerator suitGen;

/**
 * Index to suits in generate1Card()
 */
public int index = 0;


//---------CONSTRUCTORS--------------//

/**
 * No argument constructor
 */
public HandGenerator()
{
	//Initialise random number and card suit generators
	numGen = new RandomNumGenerator(13);
	suitGen = new RandomSuitGenerator();
}

//--------CLASS METHODS--------------//

//---------SET METHODS---------------//

//---------GET METHODS---------------//


/**
 * Generate 1 card
 */
public String generate1Card()
{
	//The hand
	String theHand = "";

	//Generate 1 random number
	int number = numGen.nextNumber();
	//Generate a random suit
	String suit = suitGen.suits[index];
	index++;

	String value = parseHandValue(number);
	theHand = theHand + value;
	theHand = theHand + suit;

	//Return
	return theHand;
}


/**
 * Generates a two card hand
 */
public String generate2CardHand()
{

	//Initialise random number and card suit generators
	numGen = new RandomNumGenerator(13);
	suitGen = new RandomSuitGenerator();

	//All each hand will be made up of is two numbers and two suits

	//The hand
	String theHand = "";

	//Generate 2 random numbers
    int first = numGen.nextNumber();
    int second = numGen.nextNumber();

    //Generate 2 random suits
    int suitIndex = 0;
    String firstSuit = suitGen.suits[suitIndex];
    suitIndex++;
    String secondSuit = suitGen.suits[suitIndex];

    //Put all together to make a two card hand

	//Convert the first hand value to a String and add suit
	String value1 = parseHandValue(first);
	theHand = theHand + value1;
	theHand = theHand + firstSuit;

	//Add Space
	String space = " ";
	theHand = theHand + space;

	//Second value
	String value2 = parseHandValue(second);
	theHand = theHand + value2;
	theHand = theHand + secondSuit;

    //Return hand
	return theHand;

}


/**
 * Generates a five card hand
 */
public String generate5CardHand()
{
	//Initialise random number and card suit generators
	numGen = new RandomNumGenerator(13);
	suitGen = new RandomSuitGenerator();

	//The five card hand
	String theHand = "";

	//Five random face values
	int first = numGen.nextNumber();
	int second = numGen.nextNumber();
	int third = numGen.nextNumber();
	int fourth = numGen.nextNumber();
	int fifth = numGen.nextNumber();

	//Five random suits
	int suitIndex = 0;
	String firstSuit = suitGen.suits[suitIndex];
    suitIndex++;
    String secondSuit = suitGen.suits[suitIndex];
    suitIndex++;
    String thirdSuit = suitGen.suits[suitIndex];
    suitIndex++;
    String fourthSuit = suitGen.suits[suitIndex];
    suitIndex++;
    String fifthSuit = suitGen.suits[suitIndex];
    suitIndex++;

	//Put all together to get the five card hand

	String space = " ";

	//Convert each value to a string, add suit, and add to hand

	//First card
	String value1 = parseHandValue(first);
	theHand = theHand + value1;
	theHand = theHand + firstSuit;
	theHand = theHand + space;

	//Second card
	String value2 = parseHandValue(second);
	theHand = theHand + value2;
	theHand = theHand + secondSuit;
	theHand = theHand + space;

	//Third card
	String value3 = parseHandValue(third);
	theHand = theHand + value3;
	theHand = theHand + thirdSuit;
	theHand = theHand + space;

	//Fourth card
	String value4 = parseHandValue(fourth);
	theHand = theHand + value4;
	theHand = theHand + fourthSuit;
	theHand = theHand + space;

	//Final card
	String value5 = parseHandValue(fifth);
	theHand = theHand + value5;
	theHand = theHand + fifthSuit;

	//Return the hand
	return theHand;

}

//-------INSTANCE METHODS------------//

//--------OTHER METHODS--------------//

/**
 * Return the number generated by the random number
 * generator as a String
 */
private String parseHandValue(int value)
{
	switch(value)
	{
		case 1:
			return "A";
		case 2:
			return "2";
		case 3:
			return "3";
		case 4:
			return "4";
		case 5:
			return "5";
		case 6:
			return "6";
		case 7:
			return "7";
		case 8:
			return "8";
		case 9:
			return "9";
		case 10:
			return "J";
		case 11:
			return "J";
		case 12:
			return "Q";
		case 13:
			return "K";
		case 14:
			return "A";
		default:
			return "Unknown Hand Value";
	}

}


//---------TEST METHODS--------------//

/**
 * Test method
 * @param args Command line arguments
 */
public static void main(String[] args)
{
	//Hand generator Object
	HandGenerator hg = new HandGenerator();

	//Generate one card
	int counter = 0;
	while(counter < 20)
	{
		String oneCard = hg.generate1Card();
		JOptionPane.showMessageDialog(null, "Hand: "+oneCard, "One Card", JOptionPane.INFORMATION_MESSAGE);
		counter++;
	}

	//Generate a two card hand
	//String twoCardHand = hg.generate2CardHand();
	//JOptionPane.showMessageDialog(null, "Hand: "+twoCardHand, "Two Card Hand", JOptionPane.INFORMATION_MESSAGE);

	//Generate a five card hand
	//String fiveCardHand = hg.generate5CardHand();
	//JOptionPane.showMessageDialog(null, "Hand: "+fiveCardHand, "Five Card Hand", JOptionPane.INFORMATION_MESSAGE);

	System.exit(0);


}

}